releases:
- name:    doomsday
  version: 0.9.7
  url:     https://github.com/RubidiumStudios/doomsday-boshrelease/releases/download/v0.9.7/doomsday-0.9.7.tgz
  sha1:    d893fc9acc4c7b433fd551ca2fa13462cf1d8666
