releases:
- name:    doomsday
  version: 0.9.8
  url:     https://github.com/cloudfoundry-community/doomsday-boshrelease/releases/download/v0.9.8/doomsday-0.9.8.tgz
  sha1:    aaa73a9ee876524c3a8a2a7374eaef0a9d874e05
