releases:
- name:    doomsday
  version: 0.9.2
  url:     https://github.com/doomsday-project/doomsday-boshrelease/releases/download/v0.9.2/doomsday-0.9.2.tgz
  sha1:    e17a5ee70875a19926f80879e8baf9ac3244c981
