---
meta:
  doomsday:
    network: (( grab params.network || "default" )) # Used by dns for tls cert
    azs:
      - z1

params:
  ca_validity_period:   10y
  cert_validity_period: 10y
  cert_dns_name: (( concat "doomsday." meta.doomsday.network ".bosh" ))

instance_groups:
  - name: doomsday
    instances: 1
    azs:       (( grab params.availability_zones || meta.doomsday.azs ))
    networks:
      - name:  (( grab params.network || "default" ))
    vm_type:   (( grab params.vm_type || "default" ))
    stemcell:  (( grab params.stemcell || "default" ))
    jobs:
      - name: doomsday
        release: doomsday
        properties:
          debug: false

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-jammy" ))
    version: (( grab params.stemcell_version || "latest" ))
