#!/bin/bash

shopt -s nullglob

set -eu

declare -a merge
declare -a opsfiles

fail() { echo "$@" >&2 ; exit 1 ; }

merge+=( "manifests/doomsday.yml" )

for feature in ${GENESIS_REQUESTED_FEATURES[@]}; do
  case "${feature}" in
    (ocfp)
      true
      ;;
    (*)
      if [[ -s "$GENESIS_ROOT/ops/${feature}.yml" ]]
      then opsfiles+=( "$GENESIS_ROOT/ops/${feature}.yml" )
      else fail "Unknown feature: '${feature}'"
      fi
      ;;
  esac
done

# TOOD: If `ocfp` then grab keys from {ocf,mgmt}/fqdns,
#       loop over them and compose a dynamic tlsclient.yml add hosts to merge.
#       Similarly for other items to monitor, gather inventory and add to this.
if want_feature ocfp
then merge+=( "ocfp/ocfp.yml" )
fi

for opsfile in ${opsfiles[@]}
do merge+=( "$opsfile" )
done

echo ${merge[@]}
