#!/usr/bin/env bash

if [[ -n "$GENESIS_CLOUD_CONFIG" ]]
then
  if want_feature ocfp
  then
    _env_scale="$(lookup params.ocfp_env_scale "dev")"
    _vm_type="default-${_env_scale}"
    _disk_type="default-${_env_scale}"
    _network="${GENESIS_ENVIRONMENT}-doomsday"
  else # Legacy was hard coded
    _vm_type="$(lookup params.vm_type "default" )"
    _network="$(lookup params.network "default" )"
  fi
  
  cloud_config_needs vm_type   "$(lookup params.vm_type   ${_vm_type})"
  cloud_config_needs network   "$(lookup params.network   ${_network})"
  
  if check_cloud_config
  then describe "  cloud config [#G{OK}]"
  else describe "  cloud config [#R{FAILED}]" ; exit 1
  fi
fi

exit 0
