#!/usr/bin/env bash

if want_feature ocfp ; then
  _env_scale="$(lookup --partial meta.ocfp.env.scale)"
  jobs=( doomsday )
  for job in ${jobs[@]} ; do
    _vm_type="${job}-${_env_scale}"
    _disk_type="${job}-${_env_scale}"
    _network="${GENESIS_ENVIRONMENT}-ocf"

    cloud_config_needs vm_type   "$(lookup params.vm_type   ${_vm_type})"
    cloud_config_needs network   "$(lookup params.network   ${_network})"
    cloud_config_needs disk_type "$(lookup params.disk_pool ${_disk_type})"
  done
fi

