#!/usr/bin/env bash

declare feature
declare -a features ; features=()

for feature in ${GENESIS_REQUESTED_FEATURES}
do
  case ${feature} in
    (ocfp) # OCFP Reference Architecture default features
      features+=( ${feature} )
      for f in userpass tls lb
      do want_feature ${f} || features+=( ${f} )
      done
      ;;
    (*)
      features+=( ${feature} )
      ;;
  esac
done

for feature in "${features[@]}"
do echo ${feature}
done

exit 0
