---
meta:
  admin_username:      (( vault meta.vault "/user:username" ))
  admin_password:      (( vault meta.vault "/user:password" ))
  server_auth_timeout: (( grab params.server_auth_timeout || 30 ))
  server_auth_refresh: (( grab params.server_auth_refresh || true ))

exodus:
  admin_username: (( grab meta.server_admin_username ))
  admin_password: (( grab meta.server_admin_password ))

instance_groups:
  - name: doomsday
    jobs:
      - name: doomsday
        properties:
          server:
            auth:
              type: userpass
              properties:
                username: (( grab meta.admin_username ))
                password: (( grab meta.admin_password ))
                timeout:  (( grab meta.server_auth_timeout ))
                refresh:  (( grab meta.server_auth_refresh ))

